config/routes.rb
Game::Application.routes.draw do
  match '/' => 'tops#index'

  resources :tops do
    collection do
      get :js
      get :test
      get :pjax
    end
  end

  resources :mains do
    collection do
      get :reset, :move_field, :delete_hand, :delete_field
      post :draw
    end
  end

  resources :decks do
    member do
      get :add, :delete
    end
  end

  match "/auth/:provider/callback" => "sessions#callback"

end

app/models/account.rb
class Account < ActiveRecord::Base
end

app/models/card.rb
class Card < ActiveRecord::Base

  [1, 2].each do |i|
    define_method("skill#{i}") do
      return "" if skill_name(i).blank?

      "#{skill_name(i)}(#{self["skill#{i}_damage".to_sym]}/#{self["skill#{i}_cost".to_sym]})"
    end
  end

  def skill_name(index)
    self["skill#{index}_name".to_sym]
  end
end

app/models/card_race.rb
class CardRace < ActiveRecord::Base
  belongs_to :card
  belongs_to :race
end

app/models/deck.rb
class Deck < ActiveRecord::Base
  belongs_to :card
end

app/models/race.rb
class Race < ActiveRecord::Base
  has_many :card_races, :dependent => :destroy
  has_many :cards, :through => :card_races
end

app/models/script.rb
# coding: utf-8

class Script < ActiveRecord::Base
  # associations

  # validations
  validates :name, :key, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/decks_controller.rb
# coding: utf-8

class DecksController < ApplicationController
  before_filter do
    @key = params[:id]
    @decks = Deck.where(:key => @key).order(:card_id)
  end

  def edit
    @cards = Card.all
  end

  def add
    return redirect_to edit_deck_path(@key) if Deck.where(:key => @key, :card_id => params[:card_id]).count >= 3
    Deck.create! :key => @key, :card_id => params[:card_id]
    return redirect_to edit_deck_path(@key)
  end

  def delete
    Deck.delete(params[:deck_id])
    return redirect_to edit_deck_path(@key)
  end
end

app/controllers/mains_controller.rb
# coding: utf-8

class MainsController < ApplicationController

  class FieldInfo
    def initialize(key)
      @key = key
    end

    def reset
      Rails.cache.delete("deck_#{@key}")
      Rails.cache.delete("mount_#{@key}")
      Rails.cache.delete("hand_#{@key}")
      Rails.cache.delete("field_#{@key}")
    end

    def mount
      @mount = Rails.cache.fetch("mount_#{@key}") do
        deck
      end
    end

    def deck
      @decks = Rails.cache.fetch("deck_#{@key}") do
        Deck.where(:key => @key).all.shuffle
      end
    end

    def field
      @fields = Rails.cache.fetch("field_#{@key}") do
        []
      end
    end

    def hand
      @hand = Rails.cache.fetch("hand_#{@key}") do
        []
      end
    end

    def hand_delete(deck_id)
      Rails.cache.write "hand_#{@key}", hand.reject { |d| d.id == deck_id.to_i }
    end

    def field_delete(deck_id)
      Rails.cache.write "field_#{@key}", field.reject { |d| d.id == deck_id.to_i }
    end

    def move_field(deck_id)
      deck = hand[hand.map(&:id).index(deck_id.to_i)]
      Rails.cache.write "field_#{@key}", field + [deck]
      Rails.cache.write "hand_#{@key}", hand.reject { |d| d.id == deck_id.to_i }
    end

    def draw
      Rails.cache.write "hand_#{@key}", hand + [mount[0]]
      Rails.cache.write "mount_#{@key}", mount[1, mount.size - 1]
    end
  end

  before_filter do
    @target = FieldInfo.new("target")
    @my = FieldInfo.new("my")
  end

  def reset
    @target.reset
    @my.reset
    render :action => :index
  end

  def draw
    case params[:type]
    when "my"
      @my.draw
    when "target"
      @target.draw
    end
    render :action => :index
  end

  def move_field
    case params[:type]
    when "my"
      @my.move_field(params[:id])
    when "target"
      @target.move_field(params[:id])
    end
    render :action => :index
  end

  def delete_hand
    case params[:type]
    when "my"
      @my.hand_delete(params[:id])
    when "target"
      @target.hand_delete(params[:id])
    end
    render :action => :index
  end

  def delete_field
    case params[:type]
    when "my"
      @my.field_delete(params[:id])
    when "target"
      @target.field_delete(params[:id])
    end
    render :action => :index
  end
end

app/controllers/sessions_controller.rb
# coding: utf-8

class SessionsController < ApplicationController
  # 外部認証コールバック
  def callback
  end
end

app/controllers/tops_controller.rb
# coding: utf-8

class TopsController < ApplicationController
  class Message
    def initialize(my, other)
      @my = my
      @other = other
    end

    def announce(text)
      @other.each do |id|
        $redis.rpush(id, text)
      end
    end

    def get
      $redis.lpop(@my)
    end

    def list(id=@my)
      $redis.lrange id, 0, -1
    end
  end

  def index
  end

  def pjax
  end

  def js
    i = 0
    s = params[:s].to_i
    t = params[:t].to_i

    mes = Message.new s, [t] 

    # メッセージ送ってない時だけ
    mes.announce("#{s} is Login") if mes.list(t).size == 0

    ret = mes.get || "No"
    render :json => {:result => ret}.to_json
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/decks/edit.html.erb
<%= link_to "戻る", mains_path %><br />

<span style="float:left;">
<% @cards.each do |card| %>
  <%= render :partial => "partial/card_show", :locals => {:card => card, :link => true} %>
<% end %>
</span>
<span style="clear:both;font-size:x-small;">
  <span style="font-size:x-large;"><%= @decks.size %></span>枚<br />
  <br />
  <% @decks.each do |deck| %>
    <% card = deck.card %>
    <% name = "#{card.name}(#{card.hp}/#{card.cost})　　　　[#{card.skill1}]　　[#{card.skill2}]" %>
    <%= link_to name, delete_deck_path(@key, :deck_id => deck.id) %><br />
  <% end %>
</span>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<head>
  <title>Game</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=320,user-scalable=no">
  <meta name="format-detection" content="telephone=no" />
  <meta name="format-detection" content="address=no" />
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/mains/index.html.erb
<style type="text/css">
html{background: #333;font-family: sans-serif;color: #fff;}
a {color:#fff;text-decoration: none;font-weight: bold;border-bottom: 1px dotted #fff;}
#wrapper {
  width: 950px;
  margin: 0 auto;
}
dl {
	margin: 0;
}
dt {
	font-weight: bold;
}

dt:before {
	content: "■";
}

dd {
	margin-left: 1em;
}

.singleCard {
	height:120px;
	width:90px;
	position: relative;
	border:1px solid #fff;
	border-radius: 4px;
	margin-left: 10px;
	background: #ccc;
	color: #333;
}

.singleCard a {
	color: #f00;
	
}

.cardAbility {
	position: absolute;
	top:20px;
	left: 10px;
	background: rgba(0,0,0,0.8);
	color: #fff;
	border: 1px solid rgba(255,255,255,0.5);
	-webkit-box-shadow: 10px 10px 10px 0 rgba(0,0,0,0.5);
	width: 400px;
	z-index: 10000;
	border-radius: 6px;
	display: none;
	padding: 2px;
}

.hand {
  height: 140px;
  width: 850px;
  border: solid #999 1px;
  margin: 0 auto;
  display: -webkit-box;　/* Safari,Google Chrome用 */  
  display: -moz-box;　/* Firefox用 */ 
}

.field {
  height: 160px;
  width: 950px;
  border: 1px dashed #999;
  padding: 15px;
  position: relative;
  display: -webkit-box;　/* Safari,Google Chrome用 */  
  display: -moz-box;　/* Firefox用 */ 
}

.card {
  height: 120px;
  width: 90px;
  border: 1px dashed #999;
}

.cardName {
	font-size: 1em;
}

.target_mount {
}

.my_mount {
  position: absolute;
  top: 15px;
  right: 15px;
}
</style>
<script charset="utf-8">
	$(document).ready(function(){
			$('.singleCard').click(function() {
				if ($(this).find(".cardAbility").css("display") == "none") {
					$(".cardAbility").css("display", "none");
					$(this).find(".cardAbility").css("display", "block");
				} else {
					$(this).find(".cardAbility").css("display", "none");
				}
			});
	});
</script>
<%= link_to "リセット", reset_mains_path %>&nbsp;&nbsp;<%= link_to "デッキ編集(上)", edit_deck_path("target") %>&nbsp;&nbsp;<%= link_to "デッキ編集(下)", edit_deck_path("my") %>&nbsp;&nbsp;<%= link_to "twitter  でログイン", "/auth/twitter" %>
<div id="wrapper">
  <div class="hand target_hand">
    <% @target.hand.each do |deck| %>
      <div>
        <%= render :partial => "partial/card_show", :locals => {:card => deck.card, :link => false} %>
        <%= link_to "[場]", move_field_mains_path(:type => "target", :id => deck.id) %>　<%= link_to "[削除]", delete_hand_mains_path(:type => "target", :id => deck.id) %>
      </div>
    <% end %>
  </div>
  <br />
  <div class="field">
    <div class="card target_mount">
      <%= button_to "Draw", draw_mains_path(:type => :target) %><br />
      <%= @target.mount.size %>枚
    </div>
    　
    <% @target.field.each do |deck| %>
      <div>
        <%= render :partial => "partial/card_show", :locals => {:card => deck.card, :link => false} %>
        <%= link_to "[削除]", delete_field_mains_path(:type => "target", :id => deck.id) %>
      </div>
    <% end %>
  </div>
  <br />
  <div class="field">
    <div class="card my_mount">
      <%= button_to "Draw", draw_mains_path(:type => :my) %><br />
      <%= @my.mount.size %>枚
    </div>
    <% @my.field.each do |deck| %>
      <div>
        <%= render :partial => "partial/card_show", :locals => {:card => deck.card, :link => false} %>
        <%= link_to "[削除]", delete_field_mains_path(:type => "my", :id => deck.id) %>
      </div>
    <% end %>
  </div>
  <br />
  <div class="hand my_hand">
    <% @my.hand.each do |deck| %>
      <div>
        <%= render :partial => "partial/card_show", :locals => {:card => deck.card, :link => false} %>
        <%= link_to "[場]", move_field_mains_path(:type => "my", :id => deck.id) %>　<%= link_to "[削除]", delete_hand_mains_path(:type => "my", :id => deck.id) %>
      </div>
    <% end %>
  </div>
</div>

app/views/partial/_card_show.html.erb
<div class="singleCard">
  <% if link %>
    <%= link_to card.name, add_deck_path(@key, :card_id => card.id), :class => "cardName" %><br />
    HP:<%= card.hp %><br />
    COST:<%= card.cost %><br />
  <% else %>
    <span class="cardName"><%= card.name %></span><br />
    HP:<%= card.hp %><br />
    COST:<%= card.cost %><br />
  <% end %>
  <div class="cardAbility">
  <dl>
  
  <% if card.skill1_name %>
    <dt><%= card.skill1_name %></dt>
    <dd>
    ダメージ:<%= card.skill1_damage %><br />
    コスト:<%= card.skill1_cost %><br />
    <%= truncate card.skill1_text %><br />
    </dd>
  <% end %>
  <% if card.skill2_name %>
    <dt><%= card.skill2_name %></dt>
    <dd>
    ダメージ:<%= card.skill2_damage %><br />
    コスト:<%= card.skill2_cost %><br />
    <%= truncate card.skill2_text %><br />
    </dd>
  <% end %>
  </dl>
  <%= truncate card.effect %>
  </div>
</div>

app/views/tops/index.html.erb
<%= rand(10) %>

<div class="product">
  <%= link_to "リンク押す", pjax_tops_path %><br />
</div>

<div data-pjax-container>
</div>

app/views/tops/pjax.html.erb
あいうえお

app/views/tops/test.html.erb
<script type="text/javascript">
$(function() {
  sock = new GameSocket("ws://172.16.0.156:8080");
});

function send_message()
{
  var text = $("#text2").val();
  sock.chat(text);
}
</script>
<input type="text" id="text2"/>
<input type="button" value="押す" onclick="send_message();"><br />
<br />

<style type="text/css">
.card_deck {
  height: 50px;
  width: 35px;
}

.card_hand {
  height: 80px;
  width: 56px;
}
.card_hand:hover {
  height: 160px;
  width:  112px;
  -webkit-animation: card_hand_hover;
  -webkit-animation-duration: 100ms;
  -webkit-animation-timing-function: linear;
  -webkit-transform-origin:50% 100%; 
}

@-webkit-keyframes card_hand_hover {
  0%   {height:80px; width:56px;}
  100% {height:160px; width:112px;}
}
</style>

<img src="http://img.sdgundamonline.jp/img/images/profile/20118721333460_.jpg" class="card_deck" />

<div class="card_hands">
  <img src="http://mtg.takaratomy.co.jp/product/10ed/story5/img/Slaughter.jpg" class="card_hand" />
  <img src="http://mtg.takaratomy.co.jp/product/10ed/story5/img/Slaughter.jpg" class="card_hand" />
  <img src="http://mtg.takaratomy.co.jp/product/10ed/story5/img/Slaughter.jpg" class="card_hand" />
  <img src="http://mtg.takaratomy.co.jp/product/10ed/story5/img/Slaughter.jpg" class="card_hand" />
  <img src="http://mtg.takaratomy.co.jp/product/10ed/story5/img/Slaughter.jpg" class="card_hand" />
</div>

<div id="history">
</div>